language: rust

matrix:
  include:
    - env: TARGET=thumbv6m-none-eabi
      rust: nightly-2019-01-09-x86_64-unknown-linux-gnu

install:
  - rustup target add $TARGET

script:
  - cargo build --example fsm
  - cargo build --example blink
  - cargo build --example serial-dma
  - cargo build --example serial
  - cargo build --example button
